---
# tasks file for init-ceph

- name: Check if ceph is installed
  command: ceph --version
  register: ceph_installed

# This task makes an assumption that the ceph.conf is populated by the nixos setup
- name: Retrieve the fsid from /etc/ceph/ceph.conf
  command: grep fsid /etc/ceph/ceph.conf
  register: fsid

- name: Retrieve the cluster name from /etc/ceph/ceph.conf
  command: grep "cluster name" /etc/ceph/ceph.conf
  register: cluster_name

- name: Generate monitor keyring
  become: true
  become_user: ceph
  command: ceph-authtool --create-keyring /tmp/ceph.mon.keyring --gen-key -n mon. --cap mon 'allow *'
  args:
    creates: /tmp/ceph.mon.keyring
  when: inventory_hostname == groups['mons'][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Generate client.admin keyring
  become: true
  become_user: ceph
  command: ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring --gen-key -n client.admin --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *'
  args:
    creates: /etc/ceph/ceph.client.admin.keyring
  when: inventory_hostname == groups['mons'][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Create bootstrap-osd folder
  become: true
  file:
    path: /var/lib/ceph/bootstrap-osd
    state: directory
    owner: ceph
    group: ceph
    mode: 0755

- name: Generate bootstrap-osd keyring
  become: true
  become_user: ceph
  command: ceph-authtool --create-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring --gen-key -n client.bootstrap-osd --cap mon 'profile bootstrap-osd' --cap mgr 'allow r'
  args:
    creates: /var/lib/ceph/bootstrap-osd/ceph.keyring
  when: inventory_hostname == groups['mons'][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Check if ceph.mon.keyring exists
  stat:
    path: /tmp/ceph.mon.keyring
  register: ceph_mon_keyring

- name: Check if ceph.mon.keyring already contains the client.admin key
  become: true
  become_user: ceph
  command: cat /tmp/ceph.mon.keyring
  register: ceph_mon_keyring_contents
  delegate_to: "{{ groups['mons'][0] }}"

- name: Add the client.admin generated keys to the ceph.mon.keyring
  become: true
  become_user: ceph
  command: ceph-authtool /tmp/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring
  when:
    - ceph_mon_keyring.stat.exists == True
    - ceph_mon_keyring_contents.stdout.find('client.admin') == -1
    - inventory_hostname == groups['mons'][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Add the bootstrap-osd key to the ceph.mon.keyring
  become: true
  become_user: ceph
  command: ceph-authtool /tmp/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring
  when:
    - ceph_mon_keyring.stat.exists == True
    - ceph_mon_keyring_contents.stdout.find('client.bootstrap-osd') == -1
    - inventory_hostname == groups['mons'][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Update the ownership of the ceph.mon.keyring
  become: true
  file:
    path: /tmp/ceph.mon.keyring
    owner: ceph
    group: ceph
    mode: 0600
  when: inventory_hostname == groups['mons'][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Generate the monitor map for the first monitor
  become: true
  become_user: ceph
  command: monmaptool --create --add {{ ansible_hostname }} {{ ansible_default_ipv4.address }} --fsid {{ fsid.stdout.split('=')[1] }} /tmp/monmap
  args:
    creates: /tmp/monmap
  when: inventory_hostname == groups['mons'][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Check if the monitor is already in the monmap
  command: monmaptool --print /tmp/monmap
  register: monmap_check
  delegate_to: "{{ groups['mons'][0] }}"

- name: Add the rest of the monitors to the monitor map
  become: true
  become_user: ceph
  command: monmaptool --add {{ ansible_hostname }} {{ ansible_default_ipv4.address }} --fsid {{ fsid.stdout.split('=')[1] }} /tmp/monmap
  when:
    - inventory_hostname != groups['mons'][0]
    - monmap_check.stdout.find(ansible_hostname) == -1
  delegate_to: "{{ groups['mons'][0] }}"

- name: Update the ownership of the monmap
  become: true
  file:
    path: /tmp/monmap
    owner: ceph
    group: ceph
    mode: 0644
  when: inventory_hostname == groups['mons'][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Fetch the monmap from the first monitor
  fetch:
    src: /tmp/monmap
    dest: "{{ playbook_dir }}/monmap"
    flat: yes
  when:
    - inventory_hostname == groups["mons"][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Copy the monitor map to the other nodes
  become: true
  copy:
    src: "{{ playbook_dir }}/monmap"
    remote_src: false
    dest: /tmp/monmap
    owner: "{{ ansible_user }}"
  when:
    - inventory_hostname != groups["mons"][0]

- name: Fetch the ceph.client.admin.keyring from the first monitor
  become: true
  fetch:
    src: /etc/ceph/ceph.client.admin.keyring
    dest: "{{ playbook_dir }}/ceph.client.admin.keyring"
    flat: yes
  when:
    - inventory_hostname == groups["mons"][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Copy ceph.client.admin.keyring to the other nodes
  become: true
  copy:
    src: "{{ playbook_dir }}/ceph.client.admin.keyring"
    remote_src: false
    dest: /etc/ceph/ceph.client.admin.keyring
    owner: ceph
    group: ceph
    mode: 0600
  when:
    - inventory_hostname != groups["mons"][0]

- name: Fetch the ceph.mon.keyring from the first monitor
  become: true
  fetch:
    src: /tmp/ceph.mon.keyring
    dest: "{{ playbook_dir }}/ceph.mon.keyring"
    flat: yes
  when:
    - inventory_hostname == groups["mons"][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Copy ceph.mon.keyring to the other nodes
  become: true
  copy:
    src: "{{ playbook_dir }}/ceph.mon.keyring"
    remote_src: false
    dest: /tmp/ceph.mon.keyring
    owner: ceph
    group: ceph
    mode: 0600
  when:
    - inventory_hostname != groups["mons"][0]

- name: Populate the monitor daemons with the monitor map and keyring
  become: true
  become_user: ceph
  command: ceph-mon --mkfs -i {{ ansible_hostname }} --monmap /tmp/monmap --keyring /tmp/ceph.mon.keyring
  args:
    creates: /var/lib/ceph/mon/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}/store.db
  when:
    - inventory_hostname in groups["mons"]

- name: Reset failed systemctl services
  become: true
  command: systemctl reset-failed

- name: Restart ceph-mon-{{ ansible_hostname }}
  become: true
  service:
    name: ceph-mon-{{ ansible_hostname }}
    state: restarted

- name: Create key for mgr daemon
  become: true
  command: ceph auth get-or-create mgr.{{ ansible_hostname }} osd 'allow *' mds 'allow *' mon 'allow profile mgr'
  register: ceph_mgr_key

- name: Create the /var/lib/ceph/mgr/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }} directory
  become: true
  file:
    path: /var/lib/ceph/mgr/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}
    state: directory
    owner: ceph
    group: ceph
    mode: 0755

- name: Write the mgr key to /var/lib/ceph/mgr/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}/keyring
  become: true
  become_user: ceph
  copy:
    content: "{{ ceph_mgr_key.stdout }}\n"
    dest: /var/lib/ceph/mgr/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}/keyring
    owner: ceph
    group: ceph
    mode: 0600

- name: Restart ceph-mgr-{{ ansible_hostname }}
  become: true
  service:
    name: ceph-mgr-{{ ansible_hostname }}
    state: restarted

- name: Fetch the bootstrap-osd keyring from the first monitor
  become: true
  fetch:
    src: /var/lib/ceph/bootstrap-osd/ceph.keyring
    dest: "{{ playbook_dir }}/ceph.bootstrap-osd.keyring"
    flat: yes
  when:
    - inventory_hostname == groups["mons"][0]
  delegate_to: "{{ groups['mons'][0] }}"

- name: Copy bootstrap-osd keyring to the other nodes
  become: true
  copy:
    src: "{{ playbook_dir }}/ceph.bootstrap-osd.keyring"
    remote_src: false
    dest: /var/lib/ceph/bootstrap-osd/ceph.keyring
    owner: ceph
    group: ceph
    mode: 0600
  when:
    - inventory_hostname != groups["mons"][0]

- name: Get current ceph-volume lvm inventory
  become: true
  command: ceph-volume lvm list
  register: ceph_volume_lvm
  ignore_errors: true

#- name: Get lvm volume group data
#  become: true
#  command: vgdisplay
#  register: vgdisplay
#
#- name: Wipe osd disks if not in ceph-volume lvm inventory
#  become: true
#  command: vgdestory {{ vgdispaly.stdout | regex_findall('(ceph-[0-9a-f-]+)', '\\1') | first }}
#  when:
#    - inventory_hostname in groups["osds"]
#    - ceph_volume_lvm.stdout.find(osd_device) == -1

- name: Create ceph volume
  become: true
  command: ceph-volume lvm create --data {{ osd_device }} --no-systemd --osd-id {{ ansible_hostname[-1] }}
  args:
    creates: /var/lib/ceph/osd/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}/keyring
  when:
    - inventory_hostname in groups["osds"]
    - ceph_volume_lvm.stdout.find(osd_device) == -1

- name: Get updated ceph-volume lvm inventory
  become: true
  command: ceph-volume lvm list
  register: ceph_volume_lvm
  ignore_errors: true

- name: Retrieve the osd id from the ceph-volume lvm inventory
  debug:
    msg: "{{ ceph_volume_lvm.stdout | regex_findall('osd id[\\s]+([0-9]+)', '\\1') | first }}"

#- name: Symlink the ceph-osd data directory for systemd service
#  become: true
#  file:
#    src: "/var/lib/ceph/osd/{{ cluster_name.stdout.split('=')[1] }}-{{ ceph_volume_lvm.stdout | regex_findall('osd id[\\s]+([0-9]+)', '\\1') | first }}"
#    dest: /var/lib/ceph/osd/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}
#    state: link
#    owner: ceph
#    group: ceph
#  when:
#    - inventory_hostname in groups["osds"]
#    - ceph_volume_lvm.stdout.find(osd_device) != -1

  # TODO: This type of string splitting only works for numbers less than 10
- name: Restart ceph-osd-{{ ansible_hostname[-1] }}
  become: true
  service:
    name: ceph-osd-{{ ansible_hostname[-1] }}
    state: restarted

- name: Create the /var/lib/ceph/mds/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }} directory
  become: true
  file:
    path: /var/lib/ceph/mds/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}
    state: directory
    owner: ceph
    group: ceph
    mode: 0755

- name: Create the mds key in /var/lib/ceph/mds/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}/keyring
  become: true
  become_user: ceph
  command: ceph-authtool --create-keyring /var/lib/ceph/mds/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}/keyring --gen-key -n mds.{{ ansible_hostname }} --cap mds 'allow' --cap osd 'allow rwx' --cap mon 'allow profile mds'
  args:
    creates: /var/lib/ceph/mds/{{ cluster_name.stdout.split('=')[1] }}-{{ ansible_hostname }}/keyring
  when:
    - inventory_hostname in groups["mds"]

- name: Restart ceph-mds-{{ ansible_hostname }}
  become: true
  service:
    name: ceph-mds-{{ ansible_hostname }}
    state: restarted

- name: Security - Disable insecure global id reclaim policy
  become: true
  command: ceph config set mon auth_allow_insecure_global_id_reclaim false
  when:
    - inventory_hostname == groups['mons'][0]
