---
- hosts: all
  tasks:
    - name: Update system
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install neovim
      become: true
      apt:
        name: neovim
        state: present

  roles:
    - role: ansible-service-account
      become: true
    - role: docker
    - role: cephadm
