---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: authentik
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://charts.goauthentik.io'
      targetRevision: 2024.8.1
      chart: goauthentik/authentik
      helm:
        valueFiles:
          - $values/manage-cluster/argo/authentik/values.yml
    - path: manage-cluster/argo/authentik
      repoURL: 'git@github.com:clee231/proxmox-setup.git'
      targetRevision: HEAD
      ref: values
      directory:
        recurse: true
        include: '*.yml'
        exclude: values.yml
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
