---
# tasks file for frr
- name: Install frr
  ansible.builtin.apt:
    name: frr
    state: present
    update_cache: yes

- name: Set hispeed_interfaces fact
  ansible.builtin.set_fact:
    hispeed_interfaces: |
      [
      {% for interface in hostvars[inventory_hostname]['ansible_interfaces'] %}
      {%if interface not in ['lo', 'vmbr0'] and hostvars[inventory_hostname]['ansible_facts'][interface]['module'] == hispeed_interface_module %}
      "{{ interface }}",
      {% endif %}
      {% endfor %}
      ]
- name: Set net fact
  ansible.builtin.set_fact:
    net_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'].split('.') | format_list('{:04d}') }}"

- name: Setup FRR config
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: root
    group: root
    mode: "0644"
  vars:
    ip_cidr: "{{ hispeed_ip_cidr }}"
    net: "49.0001.{{net_ip[0]}}.{{net_ip[2]}}.{{net_ip[3]}}.00"
