---
# tasks file for frr
- name: Install frr
  ansible.builtin.apt:
    name: frr
    state: present
    update_cache: yes

- name: Set hispeed_interfaces fact
  ansible.builtin.set_fact:
    hispeed_interfaces: |
      [
      {% for interface in hostvars[inventory_hostname]['ansible_interfaces'] %}
      {%if interface not in ['lo', 'vmbr0'] and hostvars[inventory_hostname]['ansible_facts'][interface]['module'] == hispeed_interface_module %}
      "{{ interface }}",
      {% endif %}
      {% endfor %}
      ]
- name: Test net formattting
  ansible.builtin.debug:
    msg: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'].split('.') | map | int | '{:04d}'.format() }}"

- name: Setup FRR config
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: root
    group: root
    mode: 0644
  vars:
    ip_cidr: "{{ hispeed_ip_cidr }}"
    net: "49.0001.1111.1111.1111.00"
