---
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["websecure"]
    matchRule: >-
              (Host(`traefik-anibase02.chase.ninja`) && PathPrefix(`/dashboard`)) ||
              (Host(`traefik-anibase02.chase.ninja`) && PathPrefix(`/api`))

service:
  type: NodePort
  externalIPs:
    - 192.168.1.5
    - 192.168.1.6
    - 192.168.1.7
