# SPDX-License-Identifier: MIT-0
---
# tasks file for proxmox-create-cluster

- name: Get the current cluster status
  ansible.builtin.command: pvecm status
  register: pvecm_status
  changed_when: false
  ignore_errors: true

- name: Output pvecm status output
  ansible.builtin.debug:
    msg: "{{ pvecm_status }}"


# pvecm create AniBase02 --link0 10.10.0.1 --link1 10.0.0.21
- name: Create Proxmox cluster
  ansible.builtin.command: pvecm create {{ proxmox_cluster_name }}
  when: pvecm_status.stdout.find(proxmox_cluster_name) == -1 and inventory_hostname == groups['proxmox'][0]
  register: pvecm_create
  delegate_to: "{{ groups['proxmox'][0] }}"
  changed_when: pvecm_create.rc == 0
  ignore_errors: true
  run_once: true

- name: Output pvecm create output
  ansible.builtin.debug:
    msg: "{{ pvecm_create }}"

- name: Get the updated cluster status
  ansible.builtin.command: pvecm status
  register: pvecm_status
  changed_when: false
  ignore_errors: true

- name: Output pvecm status output
  ansible.builtin.debug:
    msg: "{{ pvecm_status }}"

- name: Output group vars
  ansible.builtin.debug:
    msg: "{{ hostvars[groups['proxmox'][0]]['ansible_host'] }}"

# TODO: Implement this logic
# Update /etc/hosts to contain all hostnames and IPs
# 10.10.0.1 AniBase02-1.chase.ninja AniBase02-1
# 10.10.0.2 AniBase02-2.chase.ninja AniBase02-2
# 10.10.0.3 AniBase02-3.chase.ninja AniBase02-3
# 10.0.0.21 AniBase02-1.chase.ninja AniBase02-1
# 10.0.0.22 AniBase02-2.chase.ninja AniBase02-2
# 10.0.0.23 AniBase02-3.chase.ninja AniBase02-3
#
# Node2: pvecm add AniBase02-1 --link0 10.10.0.2 --link1 10.0.0.22
# Node3: pvecm add AniBase02-1 --link0 10.10.0.3 --link1 10.0.0.23
# This command requires you to type in the root password of the host
# And verify/accept the fingerprint of the host

# - name: Join nodes to the cluster
#   ansible.builtin.command: pvecm add {{ hostvars[groups['proxmox'][0]]['ansible_host'] }}
#   when: pvecm_status.rc != 0 and pvecm_status.stdout.find(proxmox_cluster_name) == -1
#   register: pvecm_add
#   changed_when: pvecm_add.rc == 0
