---
# tasks file for cephadm
- name: Install cephadm
  become: true
  ansible.builtin.apt:
    name: cephadm
    state: present

- name: Check if ceph is already deployed
  ansible.builtin.stat:
    path: /etc/ceph/ceph.conf
  register: ceph_conf

- name: Deploy ceph on first mon
  become: true
  ansible.builtin.command: cephadm bootstrap --mon-ip {{ hostvars[groups['mons'][0]]['ansible_host'] }}
  when: not ceph_conf.stat.exists
  delegate_to: "{{ groups['mons'][0] }}"

# - name: Copy SSH key to other nodes
# 
# - name: Add other mons to ceph cluster
#   become: true
#   ansible.builtin.command: cephadm shell -- ceph orch host add {{ hostvars[item]['ansible_host'] }}
#   loop: "{{ groups['mons'] }}"
#   when: not ceph_conf.stat.exists
#   delegate_to: "{{ omit if 'mons' in group_names else groups['mons'][0] }}"
# 
