---
# tasks file for ansible-service-account
- name: Create Group
  ansible.builtin.group:
    name: "{{ groupname }}"
    state: present

- name: Make sure the 'wheel' group exists
  ansible.builtin.group:
    name: wheel
    state: present

- name: Create User
  ansible.builtin.user:
    name: "{{ username }}"
    group: "{{ groupname }}"
    groups: wheel
    home: "{{ home }}"
    shell: "{{ shell }}"
    generate_ssh_key: true
    state: present

- name: Ensure 'wheel' group is in the sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'

- name: Ensure the authorized key is in the user's .ssh/authorized_keys file
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
