---
server:
  service:
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "cd.anibase02.chase.ninja"
  autoscaling:
    enabled: true
    minReplicas: 2

redis-ha:
  enabled: true
controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicaCount: 2

configs:
  params:
    server.insecure: true
